import { SceneDefinition } from './types';

export const SCENES: SceneDefinition[] = [
  {
    id: 1,
    name: 'SCENE 1',
    subtitle: 'Motorcycle Arrival & Exterior',
    startSec: 0.0,
    endSec: 2.0,
    description: 'Exterior of a residential building entrance. Entrega especial a Córdoba. Realistic motorcycle approaching, decelerating, stopping at curb, and engine turning off.',
    audioCue: 'Motorcycle 4-stroke thumping, deceleration, engine cut-off at 1.8s',
    visualCue: 'Residential facade, daylight street view, motorcycle pulling into curb',
    cameraMovement: 'Handheld organic movement with subtle camera drift and breathing',
  },
  {
    id: 2,
    name: 'SCENE 2',
    subtitle: 'PedidosYa Box & Doorbell',
    startSec: 2.0,
    endSec: 3.5,
    description: 'Close-up of the red and grey PedidosYa insulated delivery box from image_0.png mounted on parked motorcycle. Prominent "P" logo. Camera moves towards box. Doorbell "DING-DONG" sounds.',
    audioCue: 'Realistic 2-tone "DING-DONG" doorbell chime + brief suspenseful pause',
    visualCue: 'Prominent PedidosYa logo, red thermal fabric, parked motorcycle rack',
    cameraMovement: 'Slow forward camera push-in towards the red delivery box',
  },
  {
    id: 3,
    name: 'SCENE 3',
    subtitle: 'Zipper Unzips & Thermal Interior',
    startSec: 3.5,
    endSec: 6.0,
    description: 'Extreme close-up of the PedidosYa box. Lid zipper unzips and top opens naturally. Red fabric texture, seams, and silver thermal lining visible. Warm light illuminates the contents.',
    audioCue: 'Tactile zipper friction (zzzzrrrip), nylon flap lift, warm ambient hum',
    visualCue: 'Cyan zipper pulls glide open, silver quilted foil exposed, warm golden volumetric light rays',
    cameraMovement: 'Macro close-up, perspective tilt as top flap folds open backwards',
  },
  {
    id: 4,
    name: 'SCENE 4',
    subtitle: 'Photographic Print Emerges',
    startSec: 6.0,
    endSec: 8.0,
    description: 'As the box fully opens, a high-quality photographic print emerges, clearly displaying Chinita. The photo stands upright within the glowing box with background softly blurred.',
    audioCue: 'Warm harmonic chord, subtle paper rustle',
    visualCue: 'High-res portrait print with glossy paper sheen rising upright out of the warm glow',
    cameraMovement: 'Depth-of-field rack focus (cinematic bokeh), print slowly straightens to lens',
  },
  {
    id: 5,
    name: 'SCENE 5',
    subtitle: '¡Felicidades Chinita! Celebration',
    startSec: 8.0,
    endSec: 10.0,
    description: 'The photo is centered. Large, bold, white text suddenly appears: "¡FELICIDADES CHINITA! TU PEDIDO FUE ENTREGADO!". Subtle elegant confetti animation & soft notification sound. Remains visible for final 1.5s.',
    audioCue: 'Joyful notification chime + sub-bass confirmation swell',
    visualCue: 'Bold white impact typography, floating 3D confetti particles (gold, red, cyan), verified delivery badge',
    cameraMovement: 'Locked centered hero framing with subtle celebratory gentle breathing',
  },
];
